### ISSUE TITLE
Handling 503 or similar errors

### ISSUE THREAD

**Issue by bonesoul** [amcjen/node-huntergatherer#3]
It seems the api endpoint I'm using may return some 503 errors temp.

```
503 Service Unavailable
No server is available to handle this request.
```

and the error i'm getting;

```
Request failed for URL: https://api.twitch.tv/kraken/streams?game=Hearthstone%3A
%20Heroes%20of%20Warcraft&offset=0&limit=100(null)
f:\Source\hearthbreak.com\node_modules\huntergatherer\lib\huntergatherer.js:59
        if (err || res.statusCode >= 400) {
                      ^
TypeError: Cannot read property 'statusCode' of undefined
    at f:\Source\hearthbreak.com\node_modules\huntergatherer\lib\huntergatherer.
js:59:23
    at Request._callback (f:\Source\hearthbreak.com\node_modules\huntergatherer\
lib\huntergatherer.js:127:20)
    at Request.self.callback (f:\Source\hearthbreak.com\node_modules\huntergathe
rer\node_modules\request\request.js:360:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:169:7)
    at Request.<anonymous> (f:\Source\hearthbreak.com\node_modules\huntergathere
r\node_modules\request\request.js:1202:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:166:7)
    at IncomingMessage.<anonymous> (f:\Source\hearthbreak.com\node_modules\hunte
rgatherer\node_modules\request\request.js:1150:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:340:13)
20 Apr 01:41:08 - [nodemon] app crashed - waiting for file changes before starti
ng...
```

**Comment by bonesoul** [comment]
is this still maintained?
